name: Axteroid
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.2  # Actualizamos la versión a ^1.1.2
  open_file: ^3.3.2
  permission_handler: ^11.1.0
  path_provider: ^2.0.5
  flutter_native_splash: ^1.2.0
  syncfusion_flutter_charts: ^24.2.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true